name: Run Selenium Tests in Grid with Report

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.21.0
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-retries 10
          --health-timeout 10s
          --health-start-period 10s

      chrome:
        image: selenium/node-chrome:4.21.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        options: --shm-size=2g

      firefox:
        image: selenium/node-firefox:4.21.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create reports directory
        run: mkdir -p reports

      - name: Wait for Selenium Grid to be ready
        run: |
          echo "Waiting for Selenium Grid..."
          for i in {1..15}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "Selenium Grid is ready."
              break
            fi
            echo "Waiting ($i)..."
            sleep 3
          done

      - name: Run Selenium tests in Grid
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          pytest \
            --use_grid=true \
            --browser_name=chrome,firefox \
            --html=reports/report.html \
            --self-contained-html \
            --maxfail=3 \
            --disable-warnings \
            -v

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: reports/report.html

      - name: Upload Failure Screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: reports/screenshots/*.png